<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalles</title>
    <link rel="stylesheet" href="css/style.css">



</head>

<body>

    <h1><?= $marca->marca ?></h1>
    <p><strong>Información general:</strong> <?= $marca->info_general ?></p>
    <p><strong>Cantidad de concesionarias/oficinas:</strong> <?= $marca->cant_concesionarias_ofi ?></p>
    <p><strong>Post venta:</strong> <a target="_blank" href="<?= $marca->post_venta ?>"><?= $marca->post_venta ?></a> </p>


</body>

</html>