<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="css/style.css"> 

</head>

<body>
    <footer>
        <div>
            <span>TEO IVAN BLAS GARCIA, THOMAS ARNAIZ</span>
            <br>
            <span>TPE WEB 2</span>
        </div>
    </footer>
</body>

</html>



