<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalles</title>
    <link rel="stylesheet" href="css/style.css">



</head>

<body>

    <h1><?= $car->modelo ?></h1>
    <p><strong>Año:</strong> <?= $car->año ?></p>
    <p><strong>Kilometraje:</strong> <?= $car->kilometraje ?></p>
    <p><strong>Versión:</strong> <?= $car->version ?></p>
    <p><strong>Motorización:</strong> <?= $car->motorizacion ?></p>
    <p><strong>Categoría:</strong> <?= $car->categoria ?></p>


</body>

</html>