<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregar Vehículo</title>
    <link rel="stylesheet" href="css/style.css">



</head>

<body>
    
    <h1>Agregar vehículo</h1>

    <form action="/tpeweb2/router.php?action=insertarCar" method="POST">

        <label for="id_marca">Marca:</label>
        <select name="id_marca" id="id_marca" required>
            <?php foreach ($marcas as $marca): ?>
                <option value="<?= $marca->id_marca ?>"><?= $marca->marca ?></option>
            <?php endforeach; ?>
        </select>
        <br>

        <label for="modelo">Modelo:</label>
        <input type="text" id="modelo" name="modelo" placeholder="Ej: Focus" required>
        <br>

        <label for="año">Año:</label>
        <input type="number" id="año" name="año" min="1900" max="2099" required>
        <br>

        <label for="kilometraje">Kilometraje:</label>
        <input type="number" id="kilometraje" name="kilometraje" min="-1" required>
        <br>

        <label for="version">Versión:</label>
        <input type="text" id="version" name="version" required>
        <br>

        <label for="motorizacion">Motorización:</label>
        <input type="text" id="motorizacion" name="motorizacion" required>
        <br>

        <label for="categoria">Categoría:</label>
        <input type="text" id="categoria" name="categoria" required>
        <br>

        <button type="submit">Agregar vehículo</button>    
    </form>
</body>

</html>