<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="css/style.css">

</head>

<body>

    <!-- formulario de alta de tarea -->
    <form action="do_login" method="POST">
        <div>
            <label>Usuario</label>
            <input required name="user" type="text">
        </div>

        <div>
            <label>Contraseña</label>
            <input required name="password" type="password">
        </div>

        <div>
            <?php if (!empty($error)): ?>
                <?= $error ?>
            <?php endif; ?>
        </div>

        <button type="submit">Login!</button>
    </form>

</body>

</html>